### ISSUE TITLE
Intermittent problem parsing pb files

### ISSUE THREAD

**Issue by willrogers** [dls-controls/aapy#50]
Sometimes, when parsing events from `.pb` files, I get an exception:

```
Traceback (most recent call last):
  File "bench.py", line 22, in <module>
    end)
  File "/home/hgs15624/code/python/aapy/aa/fetcher.py", line 41, in get_values
    return self._get_values(pv, start, end, count)
  File "/home/hgs15624/code/python/aapy/aa/pb.py", line 183, in _get_values
    return super(PbFetcher, self)._get_values(pv, start, end, count)
  File "/home/hgs15624/code/python/aapy/aa/fetcher.py", line 108, in _get_values
    return self._parse_raw_data(response, pv, start, end, count)
  File "/home/hgs15624/code/python/aapy/aa/pb.py", line 193, in _parse_raw_data
    return parse_pb_data(raw_data, pv, start, end, count)
  File "/home/hgs15624/code/python/aapy/aa/pb.py", line 171, in parse_pb_data
    events.append(event_from_line(line, pv, year, chunk_info.type))
  File "/home/hgs15624/code/python/aapy/aa/pb.py", line 142, in event_from_line
    raise e
  File "/home/hgs15624/code/python/aapy/aa/pb.py", line 133, in event_from_line
    event.ParseFromString(unescaped)
google.protobuf.message.DecodeError: Error parsing message
```

When this happens and I print the `bytes` from which I'm parsing (`unescaped`), I get the following:

```
[8, 227, 229, 152, 11, 16, 148, 183, 199, 1, 25, 16, 10, 164, 63, 171, 114, 64]
```

When it is working, the same event gives:

```
[8, 227, 229, 152, 11, 16, 148, 183, 199, 1, 25, 16, 27, 2, 164, 63, 171, 114, 64]
```

Note that in the broken version, the bytes are `..., 16, 10, 146, ...` and in the working version they are `..., 16, 27, 2, 164, ...`.

However, the problem is intermittent - on my test PB files (`SR-DI-DCCT-01:SIGNAL` it stops on line 2071 occasionally.

The file being read is not changing.

The actual code that does the parsing is in `google/protobuf/pyext/message.cc`:

```
2074 static PyObject* ParseFromString(CMessage* self, PyObject* arg) {               
2075   if (ScopedPyObjectPtr(Clear(self)) == NULL) {                                 
2076     return NULL;                                                                
2077   }                                                                             
2078   return MergeFromString(self, arg);                                            
2079 }  
```

**Comment by willrogers** [comment]
This happens using the `PbFileParser` too, so it's not to do with retrieving the data over the network.

**Comment by willrogers** [comment]
Another example: an event is sometimes parsed correctly as:

```
Archive event for PV SR-DI-DCCT-01:SIGNAL: timestamp 2017-08-11 08:48:47.003509 UTC value 0.1016098914 severity 0
```
When parsed correctly, the bytes is printed as 

```
b'\x08\xef\xd1\x94\t\x10\xa1\x93\xd6\x01\x19I[\x83\x18\x1b\x01\x03\xba?'
[8, 239, 209, 148, 9, 16, 161, 147, 214, 1, 25, 73, 91, 131, 24, 27, 1, 3, 186, 63]
```

When an exception is thrown, bytes are printed as 

```
b'\x08\xef\xd1\x94\t\x10\xa1\x93\xd6\x01\x19I[\x83\x18\x1b\x01\x03\xba?'
[8, 239, 209, 148, 9, 16, 161, 147, 214, 1, 25, 73, 91, 131, 24, 27, 1, 3, 186, 63]
```

These are exactly the same. When I try to parse them directly, it fails.

**Comment by willrogers** [comment]
If the parsing fails, it leaves the `ScalarDouble` object in an inconsitent state. When running the test, it parses `secondsintoyear` and `nano` correctly, but seems to have no value:

```
secondsintoyear: 19212527
nano: 3508641

```

Printing `event.val` directly returns 0.0. When it succeeds, the double value is correctly `0.1016098914`.

If I parse the same bytes in an interpreter, the same exception is raised, but this time there is an incorrect value in the `val` field:

```
secondsintoyear: 19212527
nano: 3508641
val: -2.998352968077866e-29
```

**Comment by aawdls** [comment]
I think this has the same cause as #59 . In your last example you have `\x1b\x01\x03` and this is the sort of sequence that would fall foul of this problem.

**Comment by aawdls** [comment]
I cannot reproduce this using the below script (same file and time). I conclude that #59 resolves this issue.

```
from aa import pb
t_from = datetime.datetime(2017, 8, 11, 7)
t_to = datetime.datetime(2017, 8, 11, 9)
f = pb.PbFileFetcher("/mnt/archiver1/lts/")
for i in range(10):
    f.get_values("SR-DI-DCCT-01:SIGNAL", t_from, t_to)
```
